### ISSUE TITLE
在训练过程中遇到的问题

### ISSUE THREAD

**Issue by hyh323113** [laiguokun/bert-cloth#10]
你好，我在运行main.py文件进行微调时，每次step: 3200时候就会报错
`Traceback (most recent call last):
  File "D:/bert-cloth-master/main.py", line 343, in <module>
    main()
  File "D:/bert-cloth-master/main.py", line 219, in main
    loss, acc, _, _ = model(inp, tgt)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\bert-cloth-master\pytorch_pretrained_bert\modeling.py", line 1078, in forward
    loss = self.loss(out, tgt)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\python3.7\lib\site-packages\torch\nn\functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\python3.7\lib\site-packages\torch\nn\functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: invalid argument 2: non-empty vector or matrix expected at C:/w/1/s/windows/pytorch/aten/src\THCUNN/generic/ClassNLLCriterion.cu:31
`

**Comment by henceforth1984** [comment]
你好，我遇到了一样的问题，现在你知道这是为什么了吗？

**Comment by hyh323113** [comment]
> 你好，我遇到了一样的问题，现在你知道这是为什么了吗？

我只是把train/high/high0001--high999删除掉，重新运行data_util.py文件，问题就解决了。我想应该是数据集里有部分数据有问题造成的。
不过我认为这是我们自己的问题，我的同学在他的电脑上并没有删除部分数据集，而是直接运行data_util.py文件生成.pt文件后拿去训练，也没有什么问题。

**Comment by henceforth1984** [comment]
谢谢！我在BERT-base上训练的时候就没有这个错误，BERT-large上就有问题，实在是很奇怪的BUG


发件人: hyh323113<mailto:notifications@github.com>
发送时间: 2020年4月4日 14:59
收件人: laiguokun/bert-cloth<mailto:bert-cloth@noreply.github.com>
抄送: henceforth1984<mailto:Li.Haor@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [laiguokun/bert-cloth] 在训练过程中遇到的问题 (#10)


你好，我遇到了一样的问题，现在你知道这是为什么了吗？

我只是把train/high/high0001--high999删除掉，重新运行data_util.py文件，问题就解决了。我想应该是数据集里有部分数据有问题造成的。
不过我认为这是我们自己的问题，我的同学在他的电脑上并没有删除部分数据集，而是直接运行data_util.py文件生成.pt文件后拿去训练，也没有什么问题。

―
